### ISSUE TITLE
bootstrap.sh

### ISSUE THREAD

**Issue by benmenachem** [redhat-beyond/SJMaster#6]

**Comment by ifireball** [comment]
While I may have some idea about what `bootstrap.sh` means, others may not. Please write a better PR description

**Comment by benmenachem** [comment]
To be honest I wasn't really sure what I'm suppose to do 
I went over the first challenge but didn't exactly understand what my part is 
Anyway I'm still waiting for the Django PR to be sent and approved before I start my part
